services:
  api:
    build:
      context: api
      target: frankenphp_dev
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      HOST: ${HOST}
      SERVER_NAME: api.${HOST:-localhost}, http://php:80
      FRANKENPHP_WORKER_CONFIG: watch
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      APP_ENV: "${APP_ENV:-dev}"
      # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
      DATABASE_URL: ${DATABASE_URL}
      CADDY_GLOBAL_OPTIONS: ""
    extra_hosts:
      - host.docker.internal:host-gateway
    tty: false
    volumes:
      - ./api:/app
      - ./api/Caddyfile:/etc/frankenphp/Caddyfile:ro
      - ./api/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - name: http
        target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      - name: https
        target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      - name: http3
        target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

  db:
    image: mariadb:11.6
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mysql_database:/var/lib/mysql
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE

  front:
    build:
      target: dev
      context: ./front
      dockerfile: Dockerfile
    environment:
      NUXT_PUBLIC_API_BASE_URL: ${NUXT_PUBLIC_API_BASE_URL}
    volumes:
      - ./front:/srv/app

volumes:
  mysql_database:
  caddy_data:
  caddy_config:
